### ISSUE TITLE
"Error in t1 > 0 & t2 > 0 : non-conformable arrays"

### ISSUE THREAD

**Issue by matthiasgoe** [kdonnay/mwa#1]
[FullSet_Prio.zip](https://github.com/kdonnay/mwa/files/5968892/FullSet_Prio.zip)

Hi, 

I have been trying to play around with mwa in order to estimate the effect of civilian harm from air strikes on terrorism in Iraq and Syria. I have compiled a data set containing spatial and temporal information on coalition air strikes with no reported civilian harm (control), air strikes with reported civilian harm (treatment), and incidents of terrorism (dependent) from the Global Terrorism Database. I have supplemented this data with data from the PRIO-GRID in QGIS.

I have followed the (very helpful!) instructions of the mwa package closely, at least I believe so. The first few columns of my data set look as follows:

type | timestamp | lat | lon | is_iraq | is_syria | population_density
------------ |------------ |------------ |------------ |------------ |------------ |------------ 
control | 2014-01-15 |  33.71700 | 44.67952 | 1 | 0 | 166.428101
treatment | 2014-01-15 | 32.46924 | 44.41664 | 1 | 0 | 497.653900
dependent | 2014-01-15 | 33.30357 | 44.37177 | 1 | 0 | 4497.590820

I then try to run a matched wake analysis with the following code, mostly copied from the example code in the help file: 

```
rm(list = ls())
options(java.parameters = "-Xmx1g")

library(mwa)
library(rJava)
library(readr)
library(dplyr)


#Load the Full Set with match variables 

MatchSet <- read_csv("FullSet_Prio.csv")

#Rename entries to fit mwa requirements

MatchSet <- MatchSet %>% rename(lat = latitude, lon = longitude, timestamp = date) 


# Specify required parameters:
# - 2 to 10 days in steps of 2
t_window <- c(2,10,2)
# - 2 to 10 kilometers in steps of 2
spat_window <- c(2,10,2)
# - column and entries that indicate treatment events 
treatment <- c("type","treatment")
# - column and entries that indicate control events 
control  <- c("type","control")
# - column and entries that indicate dependent events 
dependent <- c("type","dependent")
# - columns to match on
matchColumns <- c("population_density")
```

I am given two errors:

```
ATTENTION: Depending on the size of the dataset and the number of spatial and temporal windows, iterations can take some time!

matchedwake(data = MatchSet, t_window = t_window, spat_window = spat_window, ...):
Using JVM with 4.4 GB heap space...
WARNING: Could not run JVM with heap space set in options(java.parameters = "-Xmx1g").
         Restarting the R session and setting java.parameters before loading the mwa package will solve this problem!
Iterating through sliding windows and generating wakes....................[OK]
WARNING: Some wakes were incomplete and had to be disregarded.
         Please check matchedwake_log.txt for details!
Matching observations and estimating causal effect.....Error in t1 > 0 & t2 > 0 : non-conformable arrays

```

Restarting R, setting the heap space before doing anything else does unfortunately not get rid of the first error.

However, I have tried to identify the issue of the second error and, just as an experiment, have set the matching variable to "year" and "is_iraq". Despite the error about heap space still persisting, it completes the mwa and returns a neat plot and a summary without an issue. For any of the other matching variables, however, the same Error occurs.

I have attached the .csv of my preliminary data with air strikes, air strikes with civilian casualties, terror attacks and some matching variables to this post.

I'm sure the issue is somewhere on my part, but I have been struggling to figure out what it might me. 

I would be very grateful if anyone has any ideas where the problem might be, since mwa looks extremely promising for what I would like to do. 

Thank you very much in advance!

**Comment by schuttes** [comment]
Hi, 
This could be a problem with your data. The fact that it works if you match on additional variables suggests that there might simply be no matching observations for some of the wakes in the first case. This is currently not handled very well in MWA. I've also seen issues with data types, such as matching columns being of type "factor". Could you please rule that out and then do a quick test? Just add a single column to your data.frame and fill it with runif(nrow(data),0,1). Then please use that as a matching variable. If that works, you probably lack sufficient balance in population_density for generating a matched sample for certain wakes. Increasing your minimal t_window and s_window sizes might help.

**Comment by kdonnay** [comment]
@matthiasgoe: Could the advice by @schuttes resolve your issue? Please let us know if you have any further questions!

**Comment by matthiasgoe** [comment]
Hi, 
Thank you very much for your suggestions. I'm sorry that I didn't respond earlier. I now had some time to look into my problem further.

To clarify my earlier post, the error does not go away when matching on additional variables, but only when replacing the variable with another.

I think that the problem has something to do with the spatial distribution of the events, since the error also occurs when only matching on a variable that was created using `runif(nrow(data),0,1)`. When matching on, for example, `sample(c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1)`, everything still works. 

I will try around some more and also talk to my thesis supervisor, who might have some ideas as well. 

Thank you again for your time and sorry to bother you!

**Comment by kdonnay** [comment]
No worries, @matthiasgoe - our pleasure!

I think your intuition is right, it probably has something to do with the spatial distributions of events. mwa is not catching errors related to that very well right now but you can look at the "wakes" yourself to see if the distributions make sense. slidingWake() is the corresponding function in the package and you can also use it directly.

Good luck with your project and happy to see you are using mwa in your work!

**Comment by matthiasgoe** [comment]
After a few frustrating hours I finally figured out what my mistake was - I had absentmindedly fed mwa with a tibble instead of a data.frame. It works great with all variables now. Thank you again for your time, I should have checked everything more closely beforehand. Really happy about this!

**Comment by schuttes** [comment]
You're not the first person with this problem. We should catch class(data) != "data.frame" in the next release. Thanks for having reported back with the solution!
